name: ubuntu-newsblur
version: 0.1
summary: Newsblur Client for Ubuntu Devices
description: Client to read all your news from all over the Internet

parts:
  newsblur:
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_BUILD_TYPE=Release]
    source: .
    after: [desktop-qt5]
    stage-packages:
      - qml-module-qtquick2
      - qml-module-ubuntu-components
      - qml-module-ubuntu-web
      - qtdeclarative5-u1db1.0
      - ubuntu-ui-toolkit-theme
      - ubuntu-ui-toolkit-tools

apps:
  ubuntu-newsblur:
    command: desktop-launch ${SNAP}/usr/bin/newsblur
    plugs: ["unity7", "network", "opengl", "browser-support"]

